version: '2'
services:
  icp-proxy-rest:
    image:
    environment:
      REST_SYNCH_INTERVAL: 10
      REST_QUEUE_CUSTOM: "{\"hk\": \"round\", \"app\": \"round\", \"c4\": \"round\", \"zhima\": \"round\"}"
      REDIS_PORT:
      REDIS_PASSWORD:
      REDIS_HOST:
      REDIS_DB: 5
      PORT:
    ports:
    -

  icp-proxy-updater:
    image:
    environment:
      UPDATER_NAME: zhima
      UPDATE_QUEUE_KEY: all,zhima,app,rob,c4,hkex
      UPDATE_PROXY_RECORD_EXPIRE: 19200
      UPDATE_PROXY_PARSE_METHOD: "proxy_info['proxy']"
      UPDATE_PROXY_FILTER_METHOD: proxy_info
      UPDATE_PROXY_DATA_KEY: "[data]"
      UPDATE_PROXY_API_DATA_FORMAT: json
      UPDATE_INTERVAL: 10
      UPDATE_EXPIRE_TIME_DEFAULT: 30
      UPDATE_API_URL:
      REDIS_PORT:
      REDIS_PASSWORD:
      REDIS_HOST:
      REDIS_DB: 5